import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MarketMates - Social Layout",
  description: "Generated by Gabriel Oliveira",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
